### ISSUE TITLE
Regression: Exception when uploading a file

### ISSUE THREAD

**Issue by RubenGarcia** [alican/django-tus#11]
* django-tus version: branch Django3x, commit https://github.com/alican/django-tus/commit/d8cd1e94f798686c894af50a0665336bb45244cd (latest as of 25.09.2020; 08:58)
* Django version: 3.1.1
* Python version: Python 3.6.9
* Operating System: Ubuntu 18.04.5

### Description

Upload of a file using react-uploady:

		const tusEnhancer = getTusEnhancer({
		            parallel: 1,   
		        });
		const random = "asdfqwfwefiqwfpjoqwef"
		const uploader = createUploader({ 
			enhancer: tusEnhancer,
    			autoUpload: true,
    			grouped: false,
			destination: {url: "https://<host>/upload/",
			              filesParamName: random,
				      headers: {Authorization: getAuthorization()}
			},
			params: {
				project: "p",
				access: "a",
			},
			sendDataOnCreate: true,
		});
		uploader.add (file);

This code was working with the branch Django3x with the commits of three days ago (3e50ea4ae2dda4c7febb2c434b31f86d0ea3db1b), but when I updated to the latest version, I get

	"HEAD /demo/upload/268a16c9-8e06-414a-977d-c111a6431c80 HTTP/1.0" 401 40
	None
	Internal Server Error: /demo/upload/
	Traceback (most recent call last):
	  File "/home/di76gum/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
		response = get_response(request)
	  File "/home/di76gum/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
		response = wrapped_callback(request, *callback_args, **callback_kwargs)
	  File "/home/di76gum/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
		return view_func(*args, **kwargs)
	  File "/home/di76gum/it4i-new/api/irods/demo/tus.py", line 31, in myTusUpload
		return TusUpload.as_view()(*args, **kwargs)
	  File "/home/di76gum/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 70, in view
		return self.dispatch(request, *args, **kwargs)
	  File "/home/di76gum/.local/lib/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
		return bound_method(*args, **kwargs)
	  File "/home/di76gum/.local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
		return view_func(*args, **kwargs)
	  File "/home/di76gum/.local/lib/python3.6/site-packages/django_tus/views.py", line 34, in dispatch
		return super(TusUpload, self).dispatch(*args, **kwargs)
	  File "/home/di76gum/.local/lib/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
		return handler(request, *args, **kwargs)
	  File "/home/di76gum/.local/lib/python3.6/site-packages/django_tus/views.py", line 67, in post
		tus_file = TusFile.create_initial_file(metadata, file_size)
	  File "/home/di76gum/.local/lib/python3.6/site-packages/django_tus/tusfile.py", line 28, in create_initial_file
		cache.add("tus-uploads/{}/filename".format(resource_id), "{}".format(metadata.get("filename").decode('UTF-8')),
	AttributeError: 'NoneType' object has no attribute 'decode'

### What I Did

```
python3 -m pip install --upgrade https://github.com/alican/django-tus/archive/Django3x.zip
```

Workaround: I removed the line  
    filesParamName: random,
which is wrong, but that made no difference.
Then I changed the metadata to read
                        params: {
                                project: "p",
                                access: "a",
                                filename: random,
                        },
which creates a filename composed of two parts separated by "_": a random string on the left of the "_", and the filename on the right. 
A location header (https://github.com/alican/django-tus/issues/12) would help.
In addition, the filename metadata is not normative in the TUS standard https://tus.io/protocols/resumable-upload.html#upload-metadata, so it would make sense to document its use in the django-tus readme.

**Comment by alican** [comment]
That error occurs because sending of a filename is optional on client side. I'm adding now a check of the filename metadata. If no one is set, django-tus will create a random filename, because their is no other option to get the original filename.

**Comment by alican** [comment]
I fixed it with the recent pushes
