### ISSUE TITLE
Call to os.renames() removes the tus_upload directory and subsequent uploads fail.

### ISSUE THREAD

**Issue by jlmarkham** [alican/django-tus#21]
* django-tus version: 0.5.0
* Django version:  3.2
* Python version: 3.8.3
* Operating System: MacOS 10.15.7 (Catalina)

### Description

When a file is successfully uploaded, a call to os.renames() is done to 
move the uploaded file to the media directory. On MacOS, this call removes
the tus_upload directory ( and the temporary uuid names sub-directory). Any subsequent
uploads will fail the because the upload directory no longer exists.

### What I Did

Using the django_tus_example Django project, I selected a file and uploaded it. It uploaded
successfully. I tried a second file and got:

Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 29, 2021 - 19:27:36
Django version 3.2, using settings 'django_tus_example.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[29/Apr/2021 19:28:27] "POST /upload/ HTTP/1.1" 201 0
[29/Apr/2021 19:30:31] "PATCH /upload/f2c61936-9362-4cd1-b349-bd542a7e702d HTTP/1.1" 204 0
/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydevd_bundle/pydevd_cython_darwin_38_64.cpython-38-darwin.so changed, reloading.
Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
April 29, 2021 - 21:00:47
Django version 3.2, using settings 'django_tus_example.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
[29/Apr/2021 21:10:07] "GET / HTTP/1.1" 200 2683
[29/Apr/2021 21:10:07] "GET /static/tus.min.js HTTP/1.1" 304 0
[29/Apr/2021 21:10:07] "GET /static/demo.js HTTP/1.1" 304 0
[29/Apr/2021 21:10:07] "GET /static/demo.css HTTP/1.1" 304 0
[29/Apr/2021 21:10:24] "GET /static/tus.min.js.map HTTP/1.1" 404 1771
[29/Apr/2021 21:10:42] "POST /upload/ HTTP/1.1" 201 0
[29/Apr/2021 21:10:42] "POST /upload/ HTTP/1.1" 201 0
[29/Apr/2021 21:10:42] "POST /upload/ HTTP/1.1" 201 0
[29/Apr/2021 21:10:43] "PATCH /upload/58ff98c8-b5ae-4eb5-8802-a30df0a3f554 HTTP/1.1" 204 0
[29/Apr/2021 21:10:43] "PATCH /upload/5a7338e6-a59e-4acf-aa15-319d5fff7c31 HTTP/1.1" 204 0
[29/Apr/2021 21:10:43] "PATCH /upload/6bebd867-c5b7-43f0-80ce-fe5099de6f72 HTTP/1.1" 204 0
Unable to create file: [Errno 2] No such file or directory: '/Users/jeff/work/django-tus/temp_upload/tus_upload/afb2ee38-e960-420f-a1c9-88684bb142fa'
Traceback (most recent call last):
  File "/Users/jeff/.pyenv/versions/DH-3.8.0-new/lib/python3.8/site-packages/django_tus/tusfile.py", line 123, in write_init_file
    self._write_file(self.get_path(), self.file_size, b"\0")
  File "/Users/jeff/.pyenv/versions/DH-3.8.0-new/lib/python3.8/site-packages/django_tus/tusfile.py", line 111, in _write_file
    with open(path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jeff/work/django-tus/temp_upload/tus_upload/afb2ee38-e960-420f-a1c9-88684bb142fa'
[29/Apr/2021 21:10:44] "POST /upload/ HTTP/1.1" 201 0

I suggest that perhaps using shutil.move followed by shutil.rmtree() ( of the temp uuid  directory) might be a
way to avoid the issue. See https://docs.python.org/3/library/shutil.html

I suspect this may be a MacOS specific bug.

**Comment by jlmarkham** [comment]
I appears that this issue may have already been addressed as the master branch is using
rename rather than renames. It appears the pip package is (perhaps) out of date.
